trigger:
 - main
pool:
 vmImage: 'ubuntu-latest'
steps:
- script: echo "Running pipeline"
 displayName: 'Print Hello'
- script: |
  echo "Installing dependencies"
  sleep 2
  echo "Build complete"
displayName: 'Simulate Build'
